config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations' }

  scope '(:locale)', locale: /fr|en/ do
    root to: 'pages#home'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    resources :collections, only: %i[index show create edit update destroy]

    resources :items, only: %i[index show new create destroy edit update] do
      resources :reminders, only: %i[new create] do
        collection do
          get :new_outside
          post :create_outside
        end
      end
    end

    resources :reminders, only: %i[destroy index] do
      collection do
        get :new_item_outside
        post :create_item_outside
      end
      member do
        get 'accept', to: 'reminders#accept'
        delete 'decline', to: 'reminders#decline'
      end
    end

    resources :network_users, only: %i[index destroy] do
      member do
        get :accept
        delete :destroy_all_links
      end
      collection do
        get :search
      end
    end

    resources :networks, only: %i[show update] do
      resources :network_users, only: :create
    end
    get 'pages/dashboard', to: 'pages#dashboard'
    get 'pages/dashboard_admin', to: 'pages#dashboard_admin'
    get 'pages/:token', to: 'pages#user_page', as: :user_page
  end
end

app/models/reminder.rb
# frozen_string_literal: true

class Reminder < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :item, optional: true
end

app/controllers/reminders_controller.rb
# frozen_string_literal: true

class RemindersController < ApplicationController
  protect_from_forgery
  before_action :authenticate_user!
  before_action :set_active_tab, only: :index

  def index
    skip_policy_scope
    @reminders_others = current_user.reminders_others
    @ghost_reminders = current_user.ghost_reminders
    @my_reminders = current_user.my_reminders
    @validate_reminders = current_user.validate_reminders
    @waiting_reminders = current_user.waiting_reminders
    @reminder = Reminder.new
  end

  def new
    @item = Item.find(params[:item_id])
    @reminder = Reminder.new
    authorize(@reminder)
  end

  def create
    @item = Item.find(params[:item_id])
    @reminders_to_destroy = @item.reminders.where(user_id: params[:reminder][:user_id])
    @reminders_to_destroy.each(&:destroy)
    @reminder = Reminder.new(reminder_params)
    authorize(@reminder)
    @reminder.item = @item
    if @reminder.user.nil?
      render :new
    elsif @reminder.save
      redirect_to item_path(@item)
    else
      render :new
    end
  end

  def destroy
    @reminder = Reminder.find(params[:id])
    @item = @reminder.item
    authorize(@reminder)
    @reminder.destroy
    if !@reminder.ghost_item.nil?
      redirect_to reminders_path
    else
      redirect_to item_path(@item)
    end
  end

  def new_outside
    @item = Item.find(params[:item_id])
    @reminder = Reminder.new
    authorize(@reminder)
  end

  def create_outside
    @item = Item.find(params[:item_id])
    @reminder = Reminder.new(reminder_params)
    @reminder.item = @item
    authorize(@reminder)
    if @reminder.ghost_name == ''
      redirect_to new_item_reminder_path(@item)
    elsif @reminder.save
      redirect_to item_path(@item)
    else
      render :new_outside
    end
  end

  def new_item_outside
    @reminder = Reminder.new
    authorize(@reminder)
  end

  def create_item_outside
    @reminder = Reminder.new(reminder_params)
    authorize(@reminder)
    @reminder.user = current_user

    @reminder.save unless @reminder.ghost_item == '' || @reminder.ghost_name == ''
    redirect_to reminders_path
  end

  def accept
    @reminder = Reminder.find(params[:id])
    authorize(@reminder)
    if @reminder.status == 'pending'
      @reminder.status = nil
      @reminder.save
    end
    redirect_back(fallback_location: reminders_path)
  end

  def decline
    @reminder = Reminder.find(params[:id])
    authorize(@reminder)
    @reminder.destroy
    redirect_back(fallback_location: reminders_path)
  end

  private

  def reminder_params
    params.require(:reminder).permit(:user_id, :ghost_name, :ghost_item, :status)
  end

  def set_active_tab
    @active_tab = params[:tab].in?(%w[emprunts demandes add]) ? params[:tab] : 'emprunts'
  end
end

app/views/reminders/_form_item_outside.html.erb
<%= simple_form_for(reminder, url:  create_item_outside_reminders_path) do |f| %>
  <%= f.input :ghost_name, label: "Ami hors réseau" %>
  <%= f.input :ghost_item, label: "Nom de l'objet" %>
  <%= f.button :submit, class: "btn btn-primary", value: "Ajouter ce rappel"%>
<% end %>

app/views/reminders/_form_reminder.html.erb
<%= simple_form_for([item, reminder]) do |f| %>
  <%= f.association :user, label_method: :label_method, include_blank: false, prompt: "Sélectionner un ami", collection: User.select{ |user| current_user.friends.include? user }, label: false %>
  <%= f.button :submit, class: "btn btn-primary", value: "Prêter/Louer" %>
<% end %>

app/views/reminders/_form_reminder_outside.html.erb
<%= simple_form_for([item, reminder], url:  create_outside_item_reminders_path(item)) do |f| %>
  <%= f.input :ghost_name, label: "Name" %>
  <%= f.button :submit, class: "btn", id: "btn-outside-item", value: "Prêter/Louer"%>
<% end %>

app/views/reminders/index.html.erb
<div class="container container-reminders">

      <h5>Mes emprunts</h5>
      <div>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="<%= "active" if @active_tab == "emprunts" %>"><a href="#emprunts" aria-controls="emprunts" role="tab" data-toggle="tab">Empruntés</a></li>
          <li role="presentation" class="<%= "active" if @active_tab == "demandes" %>"><a href="#demandes" aria-controls="demandes" role="tab" data-toggle="tab">Demandes envoyées</a></li>
          <li role="presentation" class="<%= "active" if @active_tab == "add" %>"><a href="#add" aria-controls="add" role="tab" data-toggle="tab"><i class="fas fa-plus-circle"></i></a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="emprunts">
            <div class="row">
              <% @validate_reminders.each do |reminder| %>
                <div class="col-xs-6 col-md-4 col-lg-3">
                  <% if reminder.item.nil? %>
                    <% item_ghost = Item.new(name: reminder.ghost_item, verbe: "To Lend") %>
                    <% reminder.item = item_ghost %>
                    <%= render 'shared/card_item', item: reminder.item, ghost_reminder: reminder %>
                  <% else %>
                    <%= render 'shared/card_item', item: reminder.item %>
                  <% end %>
                </div>
              <% end %>

            </div>

          </div>

          <div role="tabpanel" class="tab-pane" id="demandes">
            <div class="row">
              <% @waiting_reminders.each do |reminder| %>
                <div class="col-xs-6 col-md-4 col-lg-3">

                    <%= render 'shared/card_item', item: reminder.item %>

                </div>
              <% end %>

            </div>
          </div>

          <div role="tabpanel" class="tab-pane" id="add">
            <div class="row">

              <h5>Ajouter un rappel</h5>
              <p class="text-rappel">Besoin de vous souvenir d'un objet que vous avez emprunté à un ami en dehors du réseau ?</p> <br>

              <%= render 'form_item_outside', reminder: @reminder %>

            </div>

          </div>

        </div>
      </div>
</div>

app/views/reminders/new.html.erb
<div class="container">

  <div class="col-xs-12 col-sm-6 col-sm-offset-3">


    <div class="form">
      <h2>Partager <%= @item.name %> </h2>
      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#inside" aria-controls="inside" role="tab" data-toggle="tab">A un ami</a></li>
        <li role="presentation"><a href="#outside" aria-controls="outside" role="tab" data-toggle="tab">En dehors de mon réseau</a></li>
      </ul>
      <!-- Tab panes -->
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="inside">
          <%= render 'form_reminder', item: @item, reminder: @reminder %>
        </div>
        <div role="tabpanel" class="tab-pane" id="outside">
          <%= render 'form_reminder_outside', item: @item, reminder: @reminder %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reminders/new_outside.html.erb
<h5>Lend to a friend not connecting on Dividi</h5>

<%= render 'form_reminder_outside', item: @item, reminder: @reminder %>