config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations' }

  scope '(:locale)', locale: /fr|en/ do
    root to: 'pages#home'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    resources :collections, only: %i[index show create edit update destroy]

    resources :items, only: %i[index show new create destroy edit update] do
      resources :reminders, only: %i[new create] do
        collection do
          get :new_outside
          post :create_outside
        end
      end
    end

    resources :reminders, only: %i[destroy index] do
      collection do
        get :new_item_outside
        post :create_item_outside
      end
      member do
        get 'accept', to: 'reminders#accept'
        delete 'decline', to: 'reminders#decline'
      end
    end

    resources :network_users, only: %i[index destroy] do
      member do
        get :accept
        delete :destroy_all_links
      end
      collection do
        get :search
      end
    end

    resources :networks, only: %i[show update] do
      resources :network_users, only: :create
    end
    get 'pages/dashboard', to: 'pages#dashboard'
    get 'pages/dashboard_admin', to: 'pages#dashboard_admin'
    get 'pages/:token', to: 'pages#user_page', as: :user_page
  end
end

app/views/shared/_avatar.html.erb
<% if size == "big" %>

  <div class="avatar avatar-big">
    <% if user_signed_in? %>
      <%= link_to edit_user_registration_path do %>
        <div class="modify">
          <i class="fas fa-pencil-alt"></i>
        </div>
      <% end %>
    <% end %>

    <% if user.nil? || !user.avatar.present? %>
      <i class="fas fa-user avatar-icon"></i>
    <% else %>
      <%= cl_image_tag user.avatar, height: 150, width: 150, crop: :fill, class: "avatar-img"  %>
    <% end %>
  </div>


<% else %>

  <div class="avatar">
    <% if user.nil? || !user.avatar.present? %>
      <i class="fas fa-user avatar-icon"></i>
    <% else %>
      <%= cl_image_tag user.avatar, height: 50, width: 50, crop: :fill, class: "avatar-img"  %>
    <% end %>
  </div>

<% end %>

app/views/shared/_avatar_name.html.erb
<div class="avatar-name">
  <%= render 'shared/avatar', user: user, size: "standard" %>

  <div class="infos-user">
    <% if user.username.nil? %>
      <%= user.email %>
    <% else %>
      <%= user.username %> <br>
      <span class="email"> <%= user.email %></span>
    <% end %>
  </div>
</div>

app/views/shared/_card_friend.html.erb
<div class="card-friend">

    <% if user.avatar.file.nil? %>
      <i class="fas fa-user avatar-icon"></i>
    <% else %>
      <%= cl_image_tag user.avatar, height: 100, width: 100, crop: :fill, class: "avatar-img" %>
    <% end %>

  <div class="infos">
    <% if user.username.nil? %>
      <%= user.email %>
    <% else %>
      <%= user.username %> <br>
      <span class="email"> <%= user.email %> </span>
    <% end %>
  </div>

  <%= render 'shared/card_friend_buttons', user: user %>

</div>

app/views/shared/_card_friend_buttons.html.erb
<% if current_user.friends.include? user %>
  Amis
  <%= link_to destroy_all_links_network_user_path(current_user.network_users.where(user: user)[0]),
  method: :delete,
  data: {confirm: "Etes-vous sur de vouloir supprimer cette relation ?"} do %>
      <i class="far fa-trash-alt"></i>
  <% end %>

<% elsif current_user.friend_requests.map { |network_user_request| network_user_request.network.user }.include? user %>
  "Demande reçue"
    <%= link_to "Accept", accept_network_user_path(user.network_users.where(user: current_user)[0]), class: "notification-btn accept" %>

    <%= link_to "Decline", network_user_path(user.network_users.where(user: current_user)[0]),
      method: :delete, data: {confirm: "Etes-vous sûr d'ignorer cette demande de mise en relation ?" },class: "notification-btn decline" %>

<% elsif current_user.pending_network_users.map(&:user).include? user %>
  "Demande envoyée"
  <%= link_to "Annuler la demande",
              network_user_path(current_user.network_users.where(user: user)[0]),
              method: :delete,
              class: 'btn btn-primary' %>
<% else %>
  <%= link_to 'Envoyer une demande',
              network_network_users_path(current_user.default_network, user: user),
              method: :post,
              class: 'btn btn-primary' %>
<% end %>

app/views/shared/_card_item.html.erb
<%= link_to item_path(item)  do %>
  <div class="card">
    <div class="waiting-answer <%= 'hidden' if !item.waiting_answer? || current_user != item.user %>"><i class="fas fa-question"></i></div>
    <div class="card-photo" style="background-image: linear-gradient(rgba(255,255,255,0.1), rgba(0,0,0,0.2)), url('<%= url_image(item) %>');">
        <div class="card-category"><%= item.category.name %></div>
    </div>
    <div class="card-footer">
      <% if item.validate_reminder %>
        <div class="card-icon icon-validate-reminder">
          <i class="fas fa-hands-helping"></i>
        </div>
      <% elsif item.available? && !item.waiting_answer? %>
        <div class="card-icon icon-available">
          <i class="fas fa-thumbs-up"></i>
        </div>
      <% elsif current_user != item.user && item.waiting_answer? %>
        <div class="card-icon icon-waiting">
          <i class="fas fa-question"></i>
        </div>
      <% end %>
      <div class="card-item-name"><%= item.name %></div>
      <div class="card-item-verb"><%= item.verbe %></div>
      <div class="card-item-description"><%= item.object_description(current_user) %></div>
    </div>
  </div>
<% end %>

app/views/shared/_card_item2.html.erb
<div class="card-container">

  <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= url_image(item) %>');">
    <% if item.id.nil? %>
      <div class="card-category">
        <i>Rappel</i>
        <%= link_to reminder_path(ghost_reminder),
        method: :delete,
        data: {confirm: "Voulez-vous supprimer ce rappel ?" }  do %>
            <i class="far fa-trash-alt"></i>
        <% end %>
      </div>
    <% else %>
      <div class="card-category"><%= item.category.name %></div>
      <%= link_to "", item_path(item), class: "card-link"  %>
    <% end %>
  </div>

  <div class="card-footer">
    <div class="card-name">
      <%= item.name %>
    </div>

    <div class="card-text">
      <%= item.text("out") %>
    </div>
  </div>

    <!-- Si propriétaire fantôme -->
    <% if item.user.nil? %>
        <% ghost_user = User.new(username: ghost_reminder.ghost_name, email: "(Hors réseau)") %>
        <div class="owner"><%= render 'shared/avatar_name', user: ghost_user, size: "standard" %></div>
    <% else %>

        <% if item.user != current_user && item.collection.user.token != params[:token] %>
          <div class="owner"><%= render 'shared/avatar_name', user: item.user, size: "standard" %></div>
        <% end %>

    <% end %>

  <div class="card-status">
    <div class="status">
      <!-- helper -->
      <i class="<%= hash_status(item)[:icon] %>" ></i> <%= hash_status(item)[:text] %>
    </div>
  </div>



  <!-- Section affichée uniquement si propriétaire de l'objet et page autre que user page -->
  <% unless item.user.nil? || item.validate_reminder.nil? %>
    <% if item.collection.user == current_user && params[:token].nil? %>
      <% if item.validate_reminder.ghost_name.nil? %>
        <div class="renter">
          <%= render 'shared/avatar_name', user: item.validate_reminder.user, size: "standard" %>
        </div>
      <% else %>

        <div class="renter">
          <% ghost_user = User.new(username: item.validate_reminder.ghost_name, email: "(Hors réseau)") %>
          <%= render 'shared/avatar_name', user: ghost_user, size: "standard" %>
        </div>

      <% end %>
    <% end %>
  <% end %>
</div>

app/views/shared/_card_network_friend_request.html.erb
<div class="notification">
  <div class="notification-body">
    <div class="notification-avatar">
      <%= link_to user_page_path(network_user.network.user.token) do %>
        <% if network_user.network.user.avatar.file.nil? %>
          <i class="fas fa-user avatar avatar-icon" ></i>
          <% else %>
          <%= render 'shared/avatar', user: network_user.network.user, size: "standard" %>
        <% end %>
      <% end %>
    </div>
    <div class="notification-text">
      <% if network_user.network.user.username.nil? %>
          <%= network_user.network.user.email %>
        <% else %>
          <%= network_user.network.user.username %>
          <br>
          <%= network_user.network.user.email %>
      <% end %>
    </div>
  </div>
  <div class="notification-button">
    <!-- Accept -->
    <%= link_to "Accept", accept_network_user_path(network_user), class: "notification-btn accept" %>
    <!-- Decline -->
    <%= link_to "Decline", network_user_path(network_user),
      method: :delete, data: {confirm: "Are you sure you want to decline this friend request ?" },class: "notification-btn decline" %>
  </div>
</div>

app/views/shared/_card_network_request_sended.html.erb
<div class="card-network">

  <%= link_to user_page_path(network_user.user.token) do  %>
    <% if network_user.user.avatar.file.nil? %>
      <i class="fas fa-user avatar avatar-icon" ></i>
    <% else %>
      <%= cl_image_tag network_user.user.avatar, height: 60, width: 60, crop: :fill, class: "avatar-img" %>
    <% end %>
  <% end %>

  <div class="infos">
    <% if network_user.user.username.nil? %>
      <%= network_user.user.email %>
    <% else %>
      <%= network_user.user.username %> <br>
      <span class="email"> <%= network_user.user.email %> </span>
    <% end %>
  </div>

  <div class="links">

    <%= link_to network_user_path(network_user),
    method: :delete,
    data: {confirm: "Are you sure you want to cancel this friend request ?" } do %>
        <i class="far fa-trash-alt"></i>
    <% end %>
  </div>

  </div>

app/views/shared/_card_send_mail.html.erb
<div class="card-friend">
  <div class="envoi-mail">
    Envoyer un mail standard <br>
    <i class="far fa-envelope"></i>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info fade in" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning fade in" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    <span class="footer-hide-on-mobile">Copyright </span>
    <span class="copyright">©</span>
    <span class="footer-hide-on-mobile"> 2018</span>
  </div>
  <div class="footer-contact">
    <i class="fas fa-envelope footer-lighter"></i>
    <span class="footer-lighter footer-hide-on-mobile"><%= t('.contact_us') %></span>
    <span>contact@dividi-project.pro</span>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <%= render 'shared/flashes' %>
  <div class="navbar-container">

    <%= link_to pages_dashboard_path, class: "navbar-brand" do %>
      <%= image_tag "logo/d-noir.png" %>
    <% end %>

    <% if user_signed_in? %>
      <div class="navbar-icons">
        <%= link_to items_path do %>
          <i class="fas fa-search"></i>
        <% end %>

        <%#= link_to reminders_path do %>
<!--           <i class="fas fa-thumbtack"></i> -->
        <%# end %>

        <%= link_to collections_path do %>
          <i class="fas fa-warehouse">
            <% unless current_user.my_pending_reminders.count == 0 %>
              <span class="badge-navbar badge-pill badge-success pull-right"><%= current_user.notifications_my_objets %> </span>
            <% end %>
          </i>
        <% end %>

        <%= link_to 'Ajouter un ami', search_network_users_path, class: "btn btn-primary" %>
<!--         #= link_to network_users_path do %>
          <i class="fas fa-users">
            # unless current_user.friend_requests.size == 0 %>
              <span class="badge-navbar badge-pill badge-success pull-right"> #= current_user.friend_requests.size %> </span>
            # end %>
          </i>
        <%# end %> -->
      </div>
    <% end %>


    <% if user_signed_in? %>
      <div class="navbar-avatar dropdown">
        <div class="dropdown-toggle" data-toggle="dropdown">
          <%= render 'shared/avatar', user: current_user, size: "standard" %>
          <i class="fas fa-caret-down"></i>
        </div>
        <!-- Menu dropdown -->
        <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu">
          <% if user_signed_in? %>
            <li>
              <%= link_to network_users_path do %>
                <i class="fas fa-users"></i> Mes amis
              <% end %>
            </li>
            <li>
              <%= link_to user_page_path(current_user.token) do %>
                <i class="fas fa-address-card"></i> Mon profil
              <% end %>
            </li>
            <hr>
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fas fa-cog"></i> <%= t(".profile", default: "Paramètres") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i> <%= t(".sign_out", default: "Se déconnecter") %>
              <% end %>
            </li>
            <% if current_user.try(:admin?)%>
              <hr>
              <li>
                <%= link_to "Dashboard", pages_dashboard_admin_path %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    <% else %>
      <%= link_to  t('sign_in'), user_session_path%></div>
    <% end %>
  </div>
</div>

app/views/shared/_search_bar.html.erb
<div class="search-bar">
  <i class="fa fa-search" aria-hidden="true"></i>
  <%= form_tag path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      placeholder: placeholder,
      class: "input"
    %>
  <% end %>
</div>