config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations' }

  scope '(:locale)', locale: /fr|en/ do
    root to: 'pages#home'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    resources :collections, only: %i[index show create edit update destroy]

    resources :items, only: %i[index show new create destroy edit update] do
      resources :reminders, only: %i[new create] do
        collection do
          get :new_outside
          post :create_outside
        end
      end
    end

    resources :reminders, only: %i[destroy index] do
      collection do
        get :new_item_outside
        post :create_item_outside
      end
      member do
        get 'accept', to: 'reminders#accept'
        delete 'decline', to: 'reminders#decline'
      end
    end

    resources :network_users, only: %i[index destroy] do
      member do
        get :accept
        delete :destroy_all_links
      end
      collection do
        get :search
      end
    end

    resources :networks, only: %i[show update] do
      resources :network_users, only: :create
    end
    get 'pages/dashboard', to: 'pages#dashboard'
    get 'pages/dashboard_admin', to: 'pages#dashboard_admin'
    get 'pages/:token', to: 'pages#user_page', as: :user_page
  end
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  searchkick

  Searchkick.search_timeout = 3

  belongs_to :collection
  belongs_to :category
  has_one :user, through: :collection
  has_many :reminders

  has_many :pending_reminders, -> { where(status: 'pending') }, class_name: 'Reminder'
  has_one :validate_reminder, -> { where(status: nil) }, class_name: 'Reminder'

  validates :name, presence: true
  validates :verbe, presence: true

  monetize :price_cents, disable_validation: true

  mount_uploader :photo, PhotoUploader

  def available?
    validate_reminder.nil?
  end

  def waiting_list?
    !pending_reminders.empty?
  end

  def waiting_answer?
    available? && waiting_list?
  end

  def loaned?
    validate_reminder && verbe == "To Lend"
  end

  def rented?
    validate_reminder && verbe == "To Rent"
  end

  def borrowable?
    verbe == 'To Lend' || verbe == 'To Rent'
  end

  def text(point_of_view)
    if point_of_view == 'out'
      case verbe
      when 'To Give' then 'Don'
      when 'To Sell' then "Vente: #{price_cents.fdiv(100).to_i}€"
      when 'To Lend' then 'Prêt'
      when 'To Rent' then "Location: #{price_cents.fdiv(100).to_i}€/jour"
      else
        verbe
      end
    else
      case verbe
      when 'To Lend' then 'Emprunté à:'
      when 'To Rent' then "Loué #{price_cents.fdiv(100).to_i}€/jour à:"
      else
        verbe
      end
    end
  end

  def my_object_description
    if available? && !waiting_list?
      'Disponible pour vos amis'
    elsif available? && waiting_list?
      'Vous avez une demande en attente de réponse'
    elsif loaned?
      "#{validate_reminder.user.username} vous l'a emprunté depuis le #{validate_reminder.created_at}"
    elsif rented?
      "#{validate_reminder.user.username} vous le loue depuis le #{validate_reminder.created_at}"
    end
  end

  def friend_object_description(current_user)
    if available? && !waiting_list?
      'Disponible'
    elsif available? && waiting_list?
      'Votre demande est en attente de réponse'
    elsif loaned? && validate_reminder.user.username == current_user.username
      "emprunté à #{user.username} depuis le #{validate_reminder.created_at}"
    elsif rented? && validate_reminder.user.username == current_user.username
      "loué à #{user.username} depuis le #{validate_reminder.created_at}"
    elsif loaned?
      "Déjà prêté"
    elsif rented?
      "Déjà loué"
    end
  end

  def object_description(current_user)
    if user == current_user
      my_object_description
    else
      friend_object_description(current_user)
    end
  end

  def self.to_give
    where(verbe: 'To Give')
  end

  def self.to_lend
    where(verbe: 'To Lend')
  end

  def self.verbes
    [['To Sell', I18n.t('items.new.sell')],
     ['To Give', I18n.t('items.new.give')],
     ['To Lend', I18n.t('items.new.lend')],
     ['To Rent', I18n.t('items.new.rent')]]
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :set_item, only: %i[show edit update destroy]
  protect_from_forgery
  before_action :authenticate_user!

  def index
    @on_items_page = true

    @where = {}
    @query = '*'
    @params_categories = []
    @params_verbes = []
    @params_states = ['Disponibles', 'Empruntés', 'Notification envoyée']

    # Filter items by category if categories are present in params
    @query = params[:query] if params[:query].present?
    if params[:category_search].present?
      @where[:category_id] = params[:category_search]
      @params_categories = params[:category_search]
    end
    if params[:verbe_search].present?
      @where[:verbe] = params[:verbe_search]
      @params_verbes = params[:verbe_search]
    end

    @scope_items = policy_scope(Item)

    @items = Item.search(@query, where: @where, scope_results: ->(r) { r.where(id: @scope_items.pluck(:id)) })

    # We only take categories of @items
    @categories = Category.all
    @verbes = Item.verbes
  end

  def show
    authorize(@item)
    @verbe = @item.verbe
  end

  def new
    @item = Item.new
    authorize(@item)
  end

  # POST /collections/:collection_id/items
  def create
    @item = Item.new(item_params)
    authorize(@item)
    @item.collection = current_user.default_collection
    if @item.save
      redirect_to item_path(@item)
    else
      render :new
    end
  end

  def edit
    authorize(@item)
  end

  def update
    authorize(@item)
    @item.update(item_params)
    redirect_to item_path(@item)
  end

  def destroy
    authorize(@item)
    @item.reminders.destroy_all
    @item.destroy
    redirect_to collections_path
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :price, :photo, :collection_id, :category_id, :verbe, :description)
  end
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
  def card_background_image_path(item)
    if item.photo.present?
      cl_image_tag item.photo, alt: item.name.to_s, class: 'image-item'
    else
      image_tag('fallback/default-picture.png', class: 'fallback')
    end
  end

  def url_image(item)
    if item.photo.present?
      item.photo
    else
      File.open("#{Rails.root}/app/assets/images/fallback/default-picture.png")
    end
  end

  # returns a hash with all the information according to the logged user

  def hash_status(item)
    status = { text: '', icon: '', button: nil, renter: nil }
    # Si item fantome
    if item.id.nil?
      status[:text] = "Je l\'emprunte"
      status[:icon] = 'fas fa-user-circle'

    # Si pas de reminder
    elsif item.reminders.size.zero?
      status[:text] = 'Disponible'
      status[:icon] = 'far fa-check-circle'
      if item.collection.user == current_user
        status[:button] = 'declare' if item.verbe == 'To Rent' || item.verbe == 'To Lend'
      else
        status[:button] = 'notifier'
      end
    elsif !item.validate_reminder.nil? # if reminder with status nil (reservation validated)
      # If the item belongs to the user
      if item.collection.user == current_user
        status[:icon] = 'far fa-times-circle'
        status[:button] = 'available again'
        # If the item is loaned to someone outside the network (no user in the database)
        status[:renter] = if item.reminders.where(status: nil)[0].user.nil?
                            User.new(username: item.reminders.where(status: nil)[0].ghost_name, email: '(Hors réseau)')
                          else
                            item.reminders.where(status: nil)[0].user
                          end
        status[:text] = if item.verbe == 'To Rent'
                          'En cours de location'
                        else
                          'En cours de prêt'
                        end
      # if the validated reminder belongs to the current_user
      elsif item.validate_reminder.user == current_user
        status[:icon] = 'fas fa-user-circle'
        status[:text] = if item.verbe == 'To Rent'
                          'Je le loue'
                        else
                          "Je l\'emprunte"
                        end
      else # the object is rented by someone else
        status[:icon] = 'far fa-times-circle'
        if item.pending_reminders.where(user: current_user).size.zero?
          status[:button] = 'notifier'
          status[:text] = 'Indisponible'
        else
          status[:button] = 'cancel'
          status[:text] = 'Indisponible, demande envoyée'
        end
      end

    elsif item.collection.user == current_user # status "pending"
      status[:text] = 'Demandes en cours'
      status[:icon] = 'far fa-question-circle'
      status[:button] = if item.borrowable?
                          'declare'
                        else
                          'delete'
                        end
    elsif !item.reminders.where(user: current_user).size.zero?
      status[:text] = 'Attente de retour'
      status[:icon] = 'far fa-question-circle'
      status[:button] = 'cancel'
    else
      status[:text] = 'Disponible'
      status[:icon] = 'far fa-check-circle'
      status[:button] = 'notifier'
    end
    status
  end

  def my_reminder(item)
    item.reminders.where(user: current_user)[0]
  end

  def button(verbe)
    if verbe == 'declare'
      link_to 'Déclarer', new_item_reminder_path(params[:id]), class: 'btn btn-primary'
    elsif verbe == 'notifier'
      link_to 'Envoyer une notification', item_reminders_path(@item,
                                                              reminder: { user_id: current_user, status: 'pending' }),
              method: :post, class: 'btn btn-primary'
    elsif verbe == 'available again'
      link_to 'Objet rendu', reminder_path(@item.validate_reminder), class: 'btn btn-primary',
                                                                     method: :delete,
                                                                     data: { confirm: 'Etes-vous à nouveau en possession de cet objet ?' }
    elsif verbe == 'cancel'
      link_to 'Annuler ma notification', reminder_path(my_reminder(@item)), class: 'btn btn-primary',
                                                                            method: :delete,
                                                                            data: { confirm: "Etes-vous sûr d'annuler cette notification ?" }
    elsif verbe == 'delete'
      link_to 'Objet vendu ou donné', item_path(@item), class: 'btn btn-primary',
                                                        method: :delete,
                                                        data: { confirm: 'Voulez-vous supprimer cet objet car il est vendu ou donné ?' }
    end
  end
end

app/views/items/_conditions.html.erb
<!-- owner -->
<% owner = (@item.collection.user == current_user) %>

<% if owner == true && @item.available?  %>

  <div class="main-btn">

    <% if  @verbe == "To Lend" || @verbe == "To Rent" %>
      <%= link_to @verbe , new_item_reminder_path(@item), method: :get, class: "btn btn-primary" %>
    <% else %>
      <div><%= @verbe %></div>
    <% end %>
  </div>

  <div class="buttons-bottom">
    <!-- edit -->
    <%= link_to edit_item_path(@item) do %>
      <i class="fas fa-pencil-alt"></i>
    <% end %>

    <!-- delete -->
    <%= link_to item_path(@item),
      method: :delete,
      data: {confirm: "Are you sure you want to delete this item ?" }, class: "little-button"  do %>
      <i class="far fa-trash-alt"></i>
    <% end %>
  </div>

<% elsif owner == true && !@item.available? %>

  <div class="main-btn">
    <%= @verbe %> <br>
    Not available <br>
    <%= link_to "Available again", reminder_path(@item.reminders[0].id), class: "btn btn-primary",
            method: :delete,
            data: {confirm: "Are you back in possession of this item ?" } %>
  </div>



<!-- 2/if not owner && object is not available -->
<% elsif !@item.reminders[0].nil? && @item.reminders[0].status.nil? %>

  <div class="main-btn">

      <div>
        <%= @verbe %> <br>
        Not available
      </div>
  </div>



<!-- if not owner && object is available -->
<% else @item.reminders[0].nil? || @item.reminders[0].status == "pending" %>

  <div class="main-btn">

    <% if  @verbe == "To Lend" || @verbe == "To Rent" %>
      <%= link_to "Reserve", item_reminders_path(@item,
      reminder: {user_id: current_user, status: "pending"}),
      method: :post, class: "btn btn-primary" %>
    <% else %>
      <div><%= @verbe %></div>
    <% end %>
  </div>

<% end %>

app/views/items/_form_item.html.erb
<%= simple_form_for(@item) do |f|%>
  <div class="form-sty"><%= f.input :name, label: t('items.new.label_name') %></div>
  <%= f.association :category, label: t('items.new.category') , prompt: t('items.new.select_category') %>

  <%= f.input :verbe, legend_tag: false, as: :radio_buttons,
    collection: Item.verbes,
    label_method: :second, value_method: :first %>
  <%= f.input :price, label: t('items.new.price') %> </li>


<div class="hr"></div>
  <div class= "form-description"><%= t('items.new.description') %></div>
  <%= f.text_area :description %>
  <%= f.input :photo, input_html: { accept: ('image') } %>
  <%= f.input :photo_cache, as: :hidden %>
  <div class="hr bottom"></div>
  <%= f.button :submit, value: button, class: "btn-primary"%>
<% end %>

app/views/items/edit.html.erb
<div class="wrapper">
      <div class="container container-form-item">
        <h1>Edit my object</h1>

        <%= render 'form_item', item: @item, button: "Update my object" %>

        <%= link_to "Back", item_path(@item) %>
      </div>
</div>

app/views/items/index.html.erb
<div class="container items-search">
  <div class="entete">
    <div>
      <h3>
        Les objets de mes amis

      </h3>
    </div>
    <%= link_to 'Ajouter un pense-bête', root_path, class: 'btn btn-primary' %>
  </div>

  <%= form_tag items_path, method: :get, id: 'filter-form' do %>

<!--     Module de recherche caché pour le moment -->
    <!--     <i class="fa fa-search" aria-hidden="true"></i>
    <%#= text_field_tag :query,
      params[:query],
      placeholder: "Chercher un objet dans mon réseau", class: 'form-control'
    %> <br> -->

    <select id="category_search" multiple placeholder="<%= @params_categories.empty? ? "Toutes catégories" : "" %>" name="category_search[]">
      <% @categories.each do |category| %>
        <option value="<%= category.id %>" <%="selected=" if @params_categories.include?(category.id.to_s) %> >
          <%= category.name %>
        </option>
      <% end %>
    </select>

<!-- Module de recherche caché pour le moment
    <select id="verbe_search" multiple placeholder="<%#= @params_verbes.empty? ? "Toutes actions" : "" %>" name="verbe_search[]">
      <%# @verbes.each do |verbe| %>
        <option value="<%#= verbe[0] %>" <%#="selected" if @params_verbes.include?(verbe[0]) %> >
          <%#= verbe[1] %>
        </option>
      <%# end %>
    </select> -->

<!--     <div class="buttons">
        <%#= submit_tag "Rechercher", class: 'btn btn-primary' %>
        <%#= link_to "Remise à zéro", items_path, class: "btn" %>
    </div> -->

    <select id="state_search" multiple placeholder="A paramétrer" name="state_search[]">
      <% @params_states.each do |state| %>
        <option value="<%= state %>" >
          <%= state %>
        </option>
      <% end %>
    </select>

  <% end %>


  <div class="results-items">
    <%= t('.results', count: @items.size) %>
    <hr>
  </div>

  <div class="row">
    <% @items.each do |item| %>
      <div class="col-sm-6 col-md-4 col-lg-3">
        <%= render 'shared/card_item', item: item %>
      </div>
    <% end %>
  </div>

  <br>

</div>

app/views/items/new.html.erb
<div class="container">
    <h1 class="form-title"><%= t('.add_title') %></h1>

    <%= render 'form_item', item: @item, button: t('.add_button') %>
</div>

app/views/items/show.html.erb
<% content_for :meta_title, @item.name %>
<% content_for :meta_description, @item.description %>
<% if @item.photo.present?
content_for :meta_image, cl_image_path(@item.photo)
end %>

<div class="container-show">

  <div class="picture">
    <%= card_background_image_path @item %>
  </div>

  <div class="describe">
    <div class="navbar-owner">
      <%= render 'shared/avatar_name', user: @item.collection.user,  size: "standard" %>
      <div class="verbe"><%=  @item.text("out") %></div>
    </div>
    <div class="infos">
      <div class="titles">
        <span class="show-category"><%= @item.category.name %></span>
        <br>
        <span class="item-name"><%= @item.name %></span>

      </div>

      <div class="description">
        <% unless @item.description.nil? || @item.description == "" %>
            <span class="title-description">Description :</span><br>
            <%= @item.description %>
        <% end %>
      </div>
      <div class="creation">

        <%= @item.created_at.strftime("Créé le %d/%m/%Y") %>
      </div>
    </div>

    <div class="actions">
      <div class="status">
        <i class="<%= hash_status(@item)[:icon] %>" ></i> <%= hash_status(@item)[:text] %>
      </div>
      <% unless hash_status(@item)[:renter].nil? %>
            <div class="avatar-name"><%= render 'shared/avatar_name', user: hash_status(@item)[:renter], size: "standard" %></div>
      <% end %>
      <% unless hash_status(@item)[:button].nil? %>
            <%= button(hash_status(@item)[:button]) %>
      <% end %>

      <% if @item.collection.user == current_user && @item.reminders.size == 0 %>
        <div class="buttons-bottom">
          <!-- edit -->
          <%= link_to edit_item_path(@item) do %>
            <i class="fas fa-pencil-alt"></i>
          <% end %>

          <!-- delete -->
          <%= link_to item_path(@item),
            method: :delete,
            data: {confirm: "Are you sure you want to delete this item ?" }, class: "little-button"  do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        </div>
      <% end %>
    </div>

    <% if @item.collection.user == current_user && !@item.pending_reminders.size.zero? %>

    <div class="waiting-list">
      File d'attente :
      <% @item.pending_reminders.each do |reminder| %>
      <div class="friend">

        <%= render 'shared/avatar_name', user: reminder.user, size: "standard" %>

        <div class="buttons">

          <% if @item.validate_reminder.nil? && @item.borrowable? %>
            <%= link_to "Accepter", accept_reminder_path(reminder), class: "btn btn-primary" %>
          <% end %>
          <%= link_to decline_reminder_path(reminder),
            method: :delete,
            data: {confirm: "Etes-vous sûr de supprimer cet ami de la file d'attente ?" }, class: "little-button"  do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
    <% end %>

  </div>
</div>